export const SET_SERVERLESS_URI = 'SET_SERVERLESS_URI';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
export const SET_SYNC_CLIENT = 'SET_SYNC_CLIENT';

export const INIT_CHAT_METRICS = 'INIT_CHAT_METRICS';
export const TERM_CHAT_METRICS = 'TERM_CHAT_METRICS';
export const CHAT_MSG_SENT = 'CHAT_MSG_SENT';
