export const SET_EXECUTION_CONTEXT = 'SET_EXECUTION_CONTEXT';
export const INIT_CHAT_METRICS = 'INIT_CHAT_METRICS';
export const TERM_CHAT_METRICS = 'TERM_CHAT_METRICS';
export const CHAT_MSG_SENT = 'CHAT_MSG_SENT';
